- README.md
This is a minor bugfix for the link to the contribution guideline in the Readme (#10).
> Fix link to contribution guideline (#10)

- .github/workflows/ci.yml
- .github/workflows/test-report.yml
This is an alternative solution for fixing #25, following the guide for [Recommended setup for public repositories](https://github.com/dorny/test-reporter?tab=readme-ov-file#recommended-setup-for-public-repositories) in [dorny/test-reporter](https://github.com/dorny/test-reporter).
> Split test report jobs into separate workflows

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
There were several links that did not work.
If the formatting changes are undesired, I can remove them again.
> Update documentation markdown files (e.g. fix links)

- CHANGELOG.md
- Reqnroll.Generator/UnitTestProvider/MsTestV2GeneratorProvider.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/TRXParser.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/TestExecutionResult.cs
- Tests/Reqnroll.GeneratorTests/UnitTestProvider/MsTestV2GeneratorProviderTests.cs
- Tests/Reqnroll.Specs/Features/RegressionTests/MsTest/GH1052.feature
- Tests/Reqnroll.Specs/StepDefinitions/ExecutionResultSteps.cs
(This is a redo of PR #52 by @livioc, to be able to fix the generation issues.)
> MsTest DataRow support

- CHANGELOG.md
- Plugins/Reqnroll.NUnit.ReqnrollPlugin/NUnitNetFrameworkTestRunSettingsProvider.cs
- Plugins/Reqnroll.NUnit.ReqnrollPlugin/RuntimePlugin.cs
- Reqnroll/DefaultTestRunContext.cs
- Reqnroll/Infrastructure/DefaultDependencyProvider.cs
- Reqnroll/Infrastructure/TestExecutionEngine.cs
- Reqnroll/TestFramework/DefaultTestRunSettingsProvider.cs
- Reqnroll/TestFramework/ITestRunSettingsProvider.cs
- Reqnroll/TestRunContext.cs
- Tests/Reqnroll.RuntimeTests/Infrastructure/TestExecutionEngineTests.cs
- Tests/Reqnroll.Specs/Features/Hooks/HookParameterInjection.feature
- docs/automation/hooks.md
Fixing #58. 
So far the `[BeforeTestRun]` / `[AfterTestRun]` hooks were resolved from the "first" test run context. This is pretty arbitrary and misleading. They should have been resolved from the test run ("global") context. 
This normally should not matter for single-threaded tests, but it seems that the way how SpecFlow v4 (and Reqnroll) invokes these hooks is different and they are not necessarily invoked from the same test thread that is used for test execution (this depends on the test execution framework probably, but with NUnit there seem to be a different thread), so anything that you register in  `[BeforeTestRun]` to the injected container might not be visible for the step definitions or scenario hooks.
This PR changes this and resolves the `[BeforeTestRun]` / `[AfterTestRun]` …
> Resolve BeforeTestRun/AfterTestRun hook dependencies from the test run (global) container instead of the test thread container

- .github/workflows/ci.yml
- CONTRIBUTING.md
- Directory.Build.rsp
- Reqnroll.Tools.MsBuild.Generation/Reqnroll.Tools.MsBuild.Generation.nuspec
- Reqnroll.Tools.MsBuild.Generation/build/Reqnroll.Tools.MsBuild.Generation.tasks
This seems to fix the problem described in this discussion:
https://github.com/orgs/reqnroll/discussions/38
It should prevent developers from setting the `MSBUILDDISABLENODEREUSE` environment variable and speed up builds slightly as the msbuild nodes will be re-used.
More details on the fix here:
https://learn.microsoft.com/en-us/visualstudio/msbuild/how-to-configure-targets-and-tasks?view=vs-2022#task-factories
> Fixing failing Reqnroll build by using TaskHostFactory

- .ncrunch/Reqnroll.TestProjectGenerator.Cli.v3.ncrunchproject
- .ncrunch/Reqnroll.TestProjectGenerator.Tests.v3.ncrunchproject
- .ncrunch/Reqnroll.TestProjectGenerator.v3.ncrunchproject
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator.Cli/ArtifactNamingConventionOverride.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator.Cli/FoldersOverride.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator.Cli/Program.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator.Cli/Reqnroll.TestProjectGenerator.Cli.csproj
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator.Tests/Reqnroll.TestProjectGenerator.Tests.csproj
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/CompileResult.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/Compiler.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/Conventions/ArtifactNamingConvention.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/Data/NuGetConfigGenerator.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/Driver/CompilationDriver.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/Driver/ProjectsDriver.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/Driver/SolutionDriver.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/Factories/BindingsGenerator/CSharp10BindingsGenerator.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/Factories/BindingsGenerator/CSharpBindingsGenerator.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/Folders.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/Helpers/FileSystemHelper.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/Helpers/FolderCleaner.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/ProcessHelper.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/ProjectBuilder.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator.csproj
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/VSTestExecutionDriver.cs
- Tests/Reqnroll.Specs/StepDefinitions/ExecutionResultSteps.cs
- Tests/Reqnroll.Specs/StepDefinitions/ProjectSteps.cs
- Tests/Reqnroll.Specs/Support/Hooks.cs
This PR contains a couple of changes to improve the E2E test stability and robustness. The "specs" tests run the E2E tests currently, but later they will be also used for "system tests" (see #62).
There are a couple of improvements included in this PR, but the most important is that it provides a solution for using cached packages. This issue we have discovered with @livioc on #54: If you modify the generation part (e.g. `MsTestV2GeneratorProvider`) and rerun the related "specs" test, the test will pick up the previously generated nuget package from the package cache and therefore the test will not reflect your changes (you still see the old behavior). 
The reason for this is that these E2E test use the generated NuGet packages for generating the sample projects. Between two compilations …
> Improve E2E test stability

- CHANGELOG.md
- Reqnroll/Bindings/CucumberExpressions/CucumberExpressionParameterTypeRegistry.cs
- Tests/Reqnroll.RuntimeTests/Bindings/CucumberExpressions/CucumberExpressionParameterTypeRegistryTests.cs
This fix causes the CucumberExpressionParameterTypeRegistry to use the FQN of the enum Types used as Cucumber Expression parameters.
- [X ] Bug fix (non-breaking change which fixes an issue).
- [X ] I've added tests for my code. (most of the time mandatory)
- [X ] I have added an entry to the changelog. (mandatory)
> Fix for 81 - Cucumber Expression using Enums errors when two enums exist with the same short name

- CHANGELOG.md
- Reqnroll.Generator/Generation/UnitTestMethodGenerator.cs
- Tests/Reqnroll.SystemTests/Generation/GenerationTestBase.cs
This fix addresses Issue #111 by modifying the generated test method code to look for the ignore tag in the ScenarioInfo.CombinedTags property at test run-time.
- [X ] Bug fix (non-breaking change which fixes an issue).
- [X ] I've added tests for my code. (most of the time mandatory)
> Fix 111 ignore attr not inherited from rule

- CHANGELOG.md
- Reqnroll/Bindings/BindingDelegateInvoker.cs
- Tests/Reqnroll.RuntimeTests/Bindings/BindingInvokerTests.cs
Fixes #120
Reqnroll (and Specflow v4,x) uses Async internally (only one code path).
To ensure the user sees no difference between the old (synchronous) implementation and the new ones the `ExecutionContext` (including `AsyncLocal`) are handled manually by Reqnroll.
This is done using `ExecutionContext.Capture()` in `BindingDelegateInvoker,InvokeInExecutionContext`.
The problem is that this only works once.
Background:
- In the first call
- `ExecutionContextHolder.Value` is null. 
- This means that `ExecutionContext.Run` is not called.
- The Binding-Method is called with the current `ExecutionContext` and modifies the `AsyncLocal`. 
- Current `ExecutionContext` is captured
-  => everything is fine.
- In the second call
- `ExecutionContextHolder.Value` is not null.
- `ExecutionContext.Run` …
> Capture ExecutionContext after every binding invoke

- CHANGELOG.md
- Plugins/Reqnroll.MSTest.Generator.ReqnrollPlugin/Reqnroll.MSTest.nuspec
- Plugins/Reqnroll.MSTest.ReqnrollPlugin/MsTestRuntimeProvider.cs
- Plugins/Reqnroll.NUnit.ReqnrollPlugin/NUnitRuntimeProvider.cs
- Plugins/Reqnroll.xUnit.ReqnrollPlugin/XUnitRuntimeProvider.cs
- Reqnroll.Generator/UnitTestProvider/MsTestGeneratorProvider.cs
- Reqnroll.TestProjectGenerator/Reqnroll.TestProjectGenerator/ProjectBuilder.cs
- Reqnroll/Infrastructure/TestExecutionEngine.cs
- Reqnroll/UnitTestProvider/IUnitTestRuntimeProvider.cs
- Tests/Reqnroll.RuntimeTests/Infrastructure/TestRunContainerBuilderTests.cs
- docs/integrations/mstest.md
This PR removes the special `DelayedFixtureTearDown` for MsTest. The workaround was used to ensure that `AfterFeature` was called after all scenarios of a feature had been called.
This is now replaced by [`ClassCleanupBehavior.EndOfClass`](https://github.com/microsoft/testfx/pull/968). This required a MsTest version of at least 2.2.8 (released end of 2021).
Rationale:
- This will allow us to move forward with [MsTest Parallelization](#119), as the current workaround doesn't properly support multiple running scenarios.
- The current workaround uses internal information from MsTest that is likely to change. It relies on the fact that all tests and the `ClassInitialize` hook running on the same thread (same `ManagedThreadId`). But this is not guaranteed by the framework and is likely to …
> MsTest: Replace DelayedFixtureTearDown special case with ClassCleanupBehavior.EndOfClass

- CHANGELOG.md
- Reqnroll/Bindings/StepArgumentTypeConverter.cs
- Tests/Reqnroll.RuntimeTests/Bindings/CucumberExpressions/CucumberExpressionIntegrationTests.cs
Fixes #71
Based on the analysis and idea of @orifn1 🙂
> Fix StackOverflowException when using [StepArgumentTransformation] with same input and output type

- CHANGELOG.md
- Plugins/Reqnroll.Autofac.ReqnrollPlugin/AutofacPlugin.cs
- Plugins/Reqnroll.Autofac.ReqnrollPlugin/ConfigurationMethodsProvider.cs
- Plugins/Reqnroll.Autofac.ReqnrollPlugin/ContainerBuilderExtensions.cs
- Plugins/Reqnroll.Autofac.ReqnrollPlugin/ContainerBuilderFinder.cs
- Plugins/Reqnroll.Autofac.ReqnrollPlugin/IConfigurationMethodsProvider.cs
- Plugins/Reqnroll.Autofac.ReqnrollPlugin/IContainerBuilderFinder.cs
- Plugins/Reqnroll.Autofac.ReqnrollPlugin/Reqnroll.Autofac.ReqnrollPlugin.csproj
- Reqnroll/BoDi/IObjectContainer.cs
- Tests/Reqnroll.PluginTests/Autofac/AutofacPluginTests.cs
- Tests/Reqnroll.PluginTests/Reqnroll.PluginTests.csproj
- Tests/Reqnroll.RuntimeTests/Reqnroll.RuntimeTests.csproj
- docs/integrations/autofac.md
> Fix #56 autofac ambiguous stepdef and hook required #127 issue

- .ncrunch/Reqnroll.xUnit.Generator.ReqnrollPlugin.v3.ncrunchproject
- .ncrunch/Reqnroll.xUnit.ReqnrollPlugin.v3.ncrunchproject
- CHANGELOG.md
- Plugins/Reqnroll.xUnit.Generator.ReqnrollPlugin/Reqnroll.xUnit.Generator.ReqnrollPlugin.csproj
- Plugins/Reqnroll.xUnit.Generator.ReqnrollPlugin/Reqnroll.xUnit.nuspec
- Plugins/Reqnroll.xUnit.ReqnrollPlugin/Reqnroll.xUnit.ReqnrollPlugin.csproj
- Tests/Reqnroll.SystemTests/Portability/PortabilityTestBase.cs
> Fix: BeforeTestRun not run in .NET462 up to .NET481 in multitarget test project (#146)

- CHANGELOG.md
- Templates/Reqnroll.Templates.DotNet/templates/reqnroll-project/StepDefinitions/CalculatorStepDefinitions.cs
Following the documentation and creating a new test project with `dotnet new reqnroll-project` then running `dotnet test` ends up with `No matching step definition found for the step. Use the following code to create one: ...`
This change adds the missing binding so following the steps in the documentation won't result in confusion anymore.
> Fix project template binding

- .github/pull_request_template.md
- CHANGELOG.md
In order to give more credit to the people who contribute to the open-source project, I recommend listing all contributors of a particular release in the change log (with GitHub handle & in alphabetical order).
My goal is to make this as an ongoing thing (everyone should add their own name as part of PR), but of course we can fix the changelog backwards as well. 
What do you think?
> Add release contributors to CHANGELOG

- CHANGELOG.md
- Reqnroll/Assist/ReqnrollDefaultValueComparerList.cs
- Reqnroll/Assist/ValueComparers/DateTimeOffsetValueComparer.cs
- Tests/Reqnroll.RuntimeTests/AssistTests/ServiceTests.cs
- Tests/Reqnroll.RuntimeTests/AssistTests/ValueComparerTests/DateTimeOffsetValueComparerTests.cs
Adds a `DateTimeOffsetValueComparer`, fixes https://github.com/reqnroll/Reqnroll/issues/179.
We mostly use `DateTimeOffset` instead of `DateTime` in our projects.
----
> Add DateTimeOffsetValueComparer

- CHANGELOG.md
- Reqnroll/Bindings/BindingFactory.cs
- Reqnroll/Bindings/BindingRegistry.cs
- Reqnroll/Bindings/Discovery/BindingSourceProcessor.cs
- Reqnroll/Bindings/IBindingFactory.cs
- Reqnroll/Bindings/IStepArgumentTransformationBinding.cs
- Reqnroll/Bindings/StepArgumentTransformationBinding.cs
- Reqnroll/Bindings/StepArgumentTypeConverter.cs
- Reqnroll/StepArgumentTransformationAttribute.cs
- Tests/Reqnroll.RuntimeTests/Bindings/BindingRegistryTests.cs
- Tests/Reqnroll.RuntimeTests/RuntimeBindingRegistryBuilderTests.cs
- Tests/Reqnroll.RuntimeTests/StepArgumentTransformationTests.cs
- Tests/Reqnroll.RuntimeTests/StepArgumentTypeConverterTest.cs
- docs/automation/step-argument-conversions.md
* Added an optional `Order` parameter for `StepArgumentTransformation` to prioritize global type handlers effectively, ensuring they're considered last when needed.
* Renamed `StepTransformationTests` file to `StepArgumentTransformationTests` as this change should've be done with [this commit](https://github.com/reqnroll/Reqnroll/commit/63181711bc88437ef2d97bff4b7482a4e4982509)
> In .NET 6 and earlier versions, the [GetMethods](https://learn.microsoft.com/en-us/dotnet/api/system.type.getmethods?view=net-8.0) method does not return methods in a particular order, such as alphabetical or declaration order. Your code must not depend on the order in which methods are returned, because that order varies. However, starting with .NET 7, the ordering is deterministic based upon the metadata …
> Added order parameter to stepArgumentTransformation to prioritize execution

- CHANGELOG.md
- Plugins/Reqnroll.Autofac.ReqnrollPlugin/AutofacTestObjectResolver.cs
- Tests/Reqnroll.PluginTests/Autofac/AutofacPluginTests.cs
> Fix: Reqnroll.Autofac: Objects registered in the global container cannot be relsolved in BeforeTestRun/AfterTestRun hooks

- CHANGELOG.md
- Reqnroll.Tools.MsBuild.Generation/CodeBehindWriter.cs
- Reqnroll.Utils/FileSystemHelper.cs
Fixes #197
When building a multi-targeted project, the build system may try to write the same file multiple times,
and this can cause an IOException ("The process cannot access the file because it is being used by another process."). See #197.
Once we move to Roslyn-based generation, this problem will go away, but for now, we use a workaround of retrying the write operation a few times (the content is anyway the same).
Fix #197 
I could not find a way to have automatic test for this. Even reproducing the issue is not trivial, even with larger feature file count.
I could only reproduce it by "slowing down" the file write, using the following method instead of `File.WriteAllText`:
```
private static void WriteAllText(string path, …
```
> Fix: Process cannot access the file when building a multi-target project

- docs/installation/setup-ide.md
- update rider documentation
- documentation being out of date caused us to spend 2-3 days trying to get rider working. 
- I was unable to figure out how to build the site for local testing so i used a online md editor but i think it display correctly. 
request & included my GitHub handle to the release contributors list.
- would be nice. looking forward to contributing any way i can. 
----
> Rider ide setup documentation

- Reqnroll/Configuration/ReqnrollJsonLocator.cs
Removed checking for config file in 2 directories above AppDomain.CurrentDomain.BaseDirectory
Let extension and runtime search for config file in same locations
Discussed in https://github.com/reqnroll/Reqnroll.VisualStudio/pull/31
> Remove obsolete config file location

- CHANGELOG.md
- Reqnroll.Tools.MsBuild.Generation/build/Reqnroll.Tools.MsBuild.Generation.props
Added registration of custom "ReqnrollFeatureFiles" type in Reqnroll.Tools.MsBuild.Generation.props
Per [suggestion](https://github.com/reqnroll/Reqnroll.Rider/issues/1#issuecomment-2050945048) from @Socolin
#57 and [issue](https://github.com/reqnroll/Reqnroll.Rider/issues/1) in Reqnroll.Rider
In my understanding this change shouldn't break anything for Visual Studio, but if i'm not correct please let me know
----
> Added registration of ReqnrollFeatureFiles for Rider/ReSharper Build

- CHANGELOG.md
- Reqnroll/Infrastructure/DefaultDependencyProvider.cs
- Reqnroll/Infrastructure/MatchArgumentCalculator.cs
- Reqnroll/Infrastructure/StepDefinitionMatchService.cs
- Tests/Reqnroll.RuntimeTests/Infrastructure/StepDefinitionMatchServiceTest.cs
As suggested in https://github.com/reqnroll/Reqnroll/pull/238#pullrequestreview-2260350422
Moved CalculateArguments to MatchArgumentCalculator. 
Allow override of how Reqnroll calculates parameters with old/legacy behavior.
- :bank: Refactoring/debt/DX (improvement to code design, tooling, etc. without changing behavior)
I don't see useful writing tests for this new class or testing _StepDefinitionMatchService_ with mock MatchArgumentCalculator.
An alternative approach can be done by just changing **CalculateArguments** to protected virtual that will not require updating tests
----
*This text was originally taken from the [template of the Cucumber project](https://github.com/cucumber/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md), then edited by hand. [You can modify the template …
> feat: move CalculateArguments to MatchArgumentCalculator

- CHANGELOG.md
- Plugins/Reqnroll.CustomPlugin/Reqnroll.CustomPlugin.nuspec
Making Nuspec file for Reqnroll.CustomPlugin correctly reference v8.0.0 of System.CodeDom.
Fixes #244
> Fixing System.CodeDom in Reqnroll.CustomPlugin Nuspec file.

- CHANGELOG.md
- Reqnroll/VersionInfo.cs
Force the VersionInfo class to use Assembly.GetExecutingAssembly() in order to reliably obtain version information about Reqnroll.
Existing code calls Assembly.GetEntryAssembly(), which would return the test framework being used (NUnit, MSTest or XUnit).
Impact of this change is limited as the only consumer within Reqnroll is the AnalyticsEventProvider.
- [x ] I've changed the behaviour of the code
- [x ] I have added an entry to the "[vNext]" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request & included my GitHub handle to the release contributors list.
> Force the VersionInfo class to use Assembly.GetExecutingAssembly() 

- CHANGELOG.md
- Reqnroll.Generator/CodeDom/CodeDomHelper.cs
- Reqnroll.Generator/Generation/ScenarioPartHelper.cs
- Tests/Reqnroll.SystemTests/Generation/GenerationTestBase.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Factories/BindingsGenerator/VbBindingsGenerator.cs
Fixes #283 
The important bit is just the removal of the unnecessary `using (new SourceLineScope(_reqnrollConfiguration, _codeDomHelper, statements, context.Document.SourceFilePath, background.Location))` line from the `ScenarioPartHelper` class, the rest is just to have a test.
----
> Fix: Reqnroll generates invalid code for rule backgrounds in Visual Basic

- CHANGELOG.md
- Reqnroll/Reqnroll.csproj
- Reqnroll/Reqnroll.nuspec
- Update Microsoft.Extensions.DependencyModel to 8.0.2
Microsoft.Extensions.DependencyModel 8.0.1 have dependency to System.Text.Json 8.0.4
System.Text.Json 8.0.4 is marked as vulnerable by microsoft
by this reason we need to update Microsoft.Extensions.DependencyModel to 8.0.2
> Update Microsoft.Extensions.DependencyModel to 8.0.2

- docs/installation/setup-ide.md
Added a line in the Visual Studio Code settings example to enable the file nesting functionality.
The proposed example was not working for me. The help menu of the property `explorer.fileNesting.patterns` showed that we need to enable it manually. 
As seen in the [Visual Studio Code default settings](https://code.visualstudio.com/docs/getstarted/settings#_default-settings), it is disabled by default.
----
> Docs: enable file nesting in vscode config file

- Tests/Reqnroll.Specs/Features/Execution/AsyncSupport.feature
- Tests/Reqnroll.Specs/StepDefinitions/ProjectSteps.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/FilesystemWriter/NewFormatProjectWriter.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/ProjectBuilder.cs
This PR reduces the number of assemblies copied to the bin directory by the `TestProjectGenerator` in the system tests. This happens because
- Fewer nuget packages are referenced
- Satellite assemblies are not copied
This reduces the bin directory size of a typical test project from 4.91 MB (98 files) to 2.46 MB (28 files).
To improve system test execution time and reduce test project dependencies (and therefore complexity).
Interestingly, on my machine, the execution time didn't change that much. But I still think the change is a win because we have less I/O and the generated projects have fewer dependencies to maintain and understand.
I have checked that all tests run successfully on my …
> SystemTests: avoid unneeded assemblies copies in Testprojects

- CHANGELOG.md
- Reqnroll.Tools.MsBuild.Generation/build/Reqnroll.Tools.MsBuild.Generation.props
- Reqnroll.Tools.MsBuild.Generation/build/Reqnroll.Tools.MsBuild.Generation.tasks
This is a re-apply of #64 by @Tiberriver256 that we had to revert because it caused problems on MacOS (#152).
As the file locking issue still happens (at least for Reqnroll contributors), the solution was still desirable, but this PR enables it for Windows only. (On Linux and macOS there is [anyway no file locking](https://unix.stackexchange.com/questions/223573/does-linux-have-file-locking-protection-when-trying-to-rename-deleting-files).)
Avoid task file locks
----
*This text was originally taken from the [template of the Cucumber project](https://github.com/cucumber/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md), then edited by hand. [You can modify the template here.](https://github.com/reqnroll/.github/edit/main/.github/P …
> Enable to use TaskHostFactory on Windows

- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Dotnet/BaseCommandBuilder.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Dotnet/CacheAndCopyCommandBuilder.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Dotnet/CommandBuilder.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Dotnet/CopyFolderCommandBuilder.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Dotnet/DotNet.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Dotnet/NewCommandBuilder.NewProjectCommandBuilder.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Dotnet/NewCommandBuilder.NewSolutionCommandBuilder.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Dotnet/NewCommandBuilder.StubNewProjectCommandBuilder.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Dotnet/NewCommandBuilder.StubNewSolutionCommandBuilder.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Dotnet/NewCommandBuilder.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Dotnet/SolutionCommandBuilder.AddProjectSolutionCommandBuilder.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Dotnet/SolutionCommandBuilder.StubAddProjectSolutionCommandBuilder.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Dotnet/SolutionCommandBuilder.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/FilesystemWriter/IProjectWriter.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/FilesystemWriter/NewFormatProjectWriter.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/FilesystemWriter/OldFormatProjectWriter.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/FilesystemWriter/SolutionWriter.cs
The `TestProjectGenerator` that is used by System Tests (and currently Specs tests as well) has been improved:
* the `dotnet new sln` and the `dotnet new classlib` commands have been replaced by a "stub" version that calls the original command first, but caches the result in the temp folder and for the next time it only copies the files
* the `dotnet sln add` command has been replaced by a stub implementation that does the same by editing the `.sln` file directly
The main motivation is performance as these three basic command take significant time in local and CI execution.
With the changes I have achieved a good performance improvement locally:
- execution time of all system tests were 213 s (3:33) before
- with the changes and empty cache: 166 s (2:46), 22% improvement
- with the …
> Improve System Test performance with stubbing dotnet new

- CHANGELOG.md
- Reqnroll.Tools.MsBuild.Generation/AssemblyResolveLogger.cs
- Tests/Reqnroll.SystemTests/Plugins/XRetryPluginTest.cs
- Tests/Reqnroll.SystemTests/Reqnroll.SystemTests.csproj
- Tests/Reqnroll.SystemTests/Resources/XRetryPlugin/XRetryPluginTestFeature.feature
- Tests/Reqnroll.SystemTests/Resources/XRetryPlugin/XRetryPluginTestStepDefinitions.cs
- Tests/Reqnroll.SystemTests/SystemTestBase.cs
When the code-behind generation runs on .NET Framework (e.g. when the project is built from Visual Studio), the assembly versions are verified strictly, so if a dependency of the Reqnroll generator is updated (e.g. System.CodeDom or Gherkin), the plugins that were compiled for an earlier version fail, although they would be compatible with the new dependency.
The solution is to hook on the assembly resolve event and if the same assembly has been loaded already, we use the loaded one even if the version number is different.
Fixes #310: Could not load System.CodeDom exception with xRetry.Reqnroll plugin.
n/a
----
*This text was originally taken from the [template of the Cucumber …
> Fix: Could not load System.CodeDom exception with xRetry.Reqnroll plugin

- CHANGELOG.md
- Reqnroll/BoDi/ObjectContainer.cs
- Tests/Reqnroll.RuntimeTests/BoDi/RegisterTypeTests.cs
Once an interface has been registered and an instance of an object for that registration has been resolved, BoDi does not allow that registration to be altered. The exception message however is vague and does not indicate which Interface registration attempt caused the exception. 
The error messages given to the BoDi exceptions have been enhanced to include type/interface information.
Ease of diagnosing error situations when enhancing Reqnroll and Plugins.
- [X ] I have added/updated tests to cover my changes.
- [ X] I have added an entry to the "[vNext]" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request & …
> Enhance bodi exceptions to include name of interface when duplicate registrations attempted

- CHANGELOG.md
- docs/guides/how-to-change-test-execution-framework.md
- docs/help/faq.md
Documentation only changes. Basic FAQ and Changing Integration Test Framework pages.
Everybody likes to have docs nobody likes to write them.
Should I aim to rewrite SpecFlow FAQ? It does not look very focused.
> Basic FAQ and Changing Integration Test Framework pages

- CHANGELOG.md
- Reqnroll.Generator/Generation/ScenarioPartHelper.cs
- Reqnroll.Generator/TestGenerator.cs
- Reqnroll.Parser/ReqnrollGherkinParser.cs
- Reqnroll.Parser/ReqnrollGherkinParserFactory.cs
- Reqnroll/Parser/ReqnrollGherkinDialectProvider.cs
When generating a Reqnroll project with many feature files, compilation can be improved (times for `BigReqnrollProject` with 500 feature files) from 5.4s to 1.1s:
- original/main 5.4s
- making FixVB RegEx static 5.2s
- don't call VBFix in C# project 2.1s
- cache gherkin dialect (provider) and avoid assembly resource loads 1.2s
- avoid enum boxing 1.1s
This PR reduces compilation time by 80% (for large projects).
Trying to improve the compilation time of Reqnroll projects.
I used the
> Improve code-behind feature file compilation speed

- CHANGELOG.md
- Reqnroll/Bindings/Reflection/BindingReflectionExtensions.cs
- Reqnroll/Bindings/Reflection/RuntimeBindingType.cs
Changed RuntimeBindingType.FullName behavior for generic types.
Before it was simple Type.FullName which is not working good for generic and nullable types.
Now it's using custom logic to provide better value for autocomplete for generic types.
Example new placeholders:
Current behavior : 
* `List<string>` => System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
* `int?` => System.Nullable`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
That is resulting bad autocomplete hints in VS Plugin. (it's using FullName as a Placeholder)
This PR will change autocomplete steps in VS to be more readable.
From placeholder: `[0, Culture=neutral, …
> Improve parameter type naming for generic types

- .github/ISSUE_TEMPLATE/bug_report.yml
Add .NET 9.0 as a target for the bug report form.
Increasing the accuracy of bug reports. Happened to notice it while reporting #379.
No checklist items. This seems to be completely internal and I don't think it needs to be publicized in any way.
----
> Add .NET 9.0 as target for bug reports

- Plugins/Reqnroll.Microsoft.Extensions.DependencyInjection.ReqnrollPlugin/DependencyInjectionPlugin.cs
- Plugins/Reqnroll.Microsoft.Extensions.DependencyInjection.ReqnrollPlugin/ScenarioDependenciesAttribute.cs
- Reqnroll.Generator/UnitTestProvider/NUnit3TestGeneratorProvider.cs
- Tests/Reqnroll.Specs/Features/RegressionTests/MsTest/ScenarioIsCorrectInParallelExecution.feature
- Tests/Reqnroll.Specs/Features/RegressionTests/NUnit/ScenarioIsCorrectInParallelExecution.feature
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Factories/ConfigurationGenerator/AppConfigGenerator.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/ProjectBuilder.cs
Searched for "specflow" and replaced links/comments with Reqnroll alternatives.
Specflow and the repro are gone, so probably all links are or will be gone soon.
Github issue 1052 can be accessed via web archive: https://web.archive.org/web/20200926191603/https://github.com/SpecFlowOSS/SpecFlow/issues/1052
> Remove Specflow remains in links and comments

- CHANGELOG.md
- Reqnroll.Tools.MsBuild.Generation/AssemblyResolveLogger.cs
- Reqnroll.Tools.MsBuild.Generation/GenerateFeatureFileCodeBehindTaskExecutor.cs
- Reqnroll.Tools.MsBuild.Generation/IProcessInfoDumper.cs
- Reqnroll.Tools.MsBuild.Generation/ITaskLoggingWrapper.cs
- Reqnroll.Tools.MsBuild.Generation/MSBuildTaskAnalyticsTransmitter.cs
- Reqnroll.Tools.MsBuild.Generation/MSBuildTraceListener.cs
- Reqnroll.Tools.MsBuild.Generation/ProcessInfoDumper.cs
- Reqnroll.Tools.MsBuild.Generation/TaskLoggingHelperWithNameTagWrapper.cs
- Reqnroll.Tools.MsBuild.Generation/build/Reqnroll.Tools.MsBuild.Generation.props
- Reqnroll.Tools.MsBuild.Generation/build/Reqnroll.Tools.MsBuild.Generation.targets
- Tests/Reqnroll.Specs/Features/Execution/Configuration.feature
- Tests/Reqnroll.Specs/StepDefinitions/ExecutionSteps.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Compiler.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Driver/CompilationDriver.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/FilesystemWriter/OldFormatProjectWriter.cs
- docs/help/troubleshooting.md
- Changed the default log level of reqnroll MsBuild messages to normal or low.
- Used [Reqnroll] prefix for all generated messages.
- Removed unused log related MSBuild configurations.
- Added an extra entry in the Troubleshooting section to highlight the additional logging option.
When generating a project with many feature files, Reqnroll will generate many log entries even if minimal logging is configured.
However, the [logging guidelines](https://learn.microsoft.com/en-us/dotnet/api/microsoft.build.framework.loggerverbosity?view=msbuild-17-netcore#remarks) state that only high importance messages should be logged when minimal detail is specified.
The detailed output happens because we currently always set a `VerboseOutput' MSBuild property to true. This has been happening since commit …
> Reduced MsBuild log output and consistent use of [Reqnroll] prefix

- CHANGELOG.md
- Plugins/Reqnroll.MSTest.ReqnrollPlugin/MSTestTraceListener.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/TRXParser.cs
When writing output, Reqnroll only uses `TestContext` and don't write to `Console`.
The same happens already for [NUnit](https://github.com/reqnroll/Reqnroll/blob/main/Plugins/Reqnroll.NUnit.ReqnrollPlugin/NUnitTraceListener.cs#L23-L25) and [xUnit](https://github.com/reqnroll/Reqnroll/blob/main/Plugins/Reqnroll.xUnit.ReqnrollPlugin/XUnitTraceListener.cs#L33-L36).
Fixes #298
This avoids duplicate output and that Console output of tests get mixed up.
Is there a particular reason why currently both `TestContext` and `Console` output is used?
> MsTest: Only use TestContext for output and not Console.WriteLine

- docs/execution/output-api.md
I changed the documentation output API constructor to contain _reqnrollOutputHelper instead of _outputHelper
I noticed this small error while reading the documentation
Not sure if refacotring the field to _outputHelper would've been more appriciated than changing the constructor
----
> Changed Output API documentation _outputHelper to _reqnrollOutputHelper in constructor

- CHANGELOG.md
- Plugins/Reqnroll.Autofac.ReqnrollPlugin/AutofacTestObjectResolver.cs
- Tests/Reqnroll.PluginTests/Autofac/AutofacPluginTests.cs
Changed Reqnroll.Autofac `AutofacTestObjectResolver` to be able to resolve object (typically Renqroll internal objects) that are registered in the Reqnroll container but not in the Autofac one.
Fixes #340 
n/a 
----
> Fix: Reqnroll.Autofac: FeatureContext cannot be resolved in BeforeFeature/AfterFeature hooks

- CHANGELOG.md
- Reqnroll.Generator/CodeDom/CodeDomHelper.cs
- Reqnroll.Generator/Generation/ScenarioPartHelper.cs
- Reqnroll.Generator/Generation/UnitTestFeatureGenerator.cs
- Reqnroll.Generator/Generation/UnitTestMethodGenerator.cs
- Reqnroll.Generator/UnitTestProvider/NUnit3TestGeneratorProvider.cs
We had built a custom CodeDomHelper function to create the "global::" prefix to Reqnroll type names in order to avoid namespace collisions with user-provided test names.
This change eliminates that custom function in favor of using the idiomatic means provided by .net: a CodeTypeReference with a constructor argument of CodeTypeReferenceOptions.GlobalReference.
Code clean-up.
- [ X] I have added an entry to the "[vNext]" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request & included my GitHub handle to the release contributors list.
> Replace custom namespace globalization with idiomatic approach

- .github/workflows/ci.yml
- docs/guides/migrating-from-specflow.md
Added documentation build to the CI pipeline
To verify doc inconsistencies, broken links, etc.
IMPORTANT: the result of this build is (currently) not used as public documentation. But the public documentation is built based on the same sources by read-the-docs.
----
> Add documentation build to the CI pipeline

- README.md
I changed the README text from supporting .NET 8 to .NET 9.
I'm currently researching Reqnroll, and it was not clear whether .NET 9.0 is supported (or not). If found the [compatibility page](https://docs.reqnroll.net/latest/installation/compatibility.html), where it clearly lists the supported OS, .NET versions, and testing frameworks and where .NET 9.0 is included.
I personally prefer the simpler to scan listing style used in the [docs page](https://docs.reqnroll.net/latest/installation/compatibility.html).
I believe the supported .NET versions are very important information and should clearly be visible on the README page of any GitHub project. It helps developers quickly decide whether this project is suitable to their needs. …
> Clarify/Add .NET 9.0 Support to README

- CHANGELOG.md
- Plugins/Reqnroll.Microsoft.Extensions.DependencyInjection.ReqnrollPlugin/InvalidScenarioDependenciesException.cs
- Plugins/Reqnroll.Microsoft.Extensions.DependencyInjection.ReqnrollPlugin/MissingScenarioDependenciesException.cs
- Plugins/Reqnroll.Microsoft.Extensions.DependencyInjection.ReqnrollPlugin/ServiceCollectionFinder.cs
- Tests/Reqnroll.PluginTests/Microsoft.Extensions.DependencyInjection/ServiceCollectionFinderTests.cs
For Reqnroll.Microsoft.Extensions.DependencyInjection improved the message when `[ScenarioDependencies]` can't be found
- Tell it should be `static` (and could be non-public)
- Tell the scanned assemblies
- Don't give a "System.ArgumentNullException : Value cannot be null" when returning the wrong type / void methods
The new messages are (see also unit tests)
- [ScenarioDependencies] should return IServiceCollection but the method doesn't return a value.
- [ScenarioDependencies] should return IServiceCollection but returned null.
- [ScenarioDependencies] should return IServiceCollection but returned System.Collections.Generic.List`1[System.String].
- No method marked with [ScenarioDependencies] attribute found. It should be a (public or non-public) static method. Scanned assemblies: …
> Improved message when [ScenarioDependencies] can't be found or has an incorrect return type (Reqnroll.Microsoft.Extensions.DependencyInjection)

- .github/ISSUE_TEMPLATE/bug_report.yml
Let users select xUnit 2 or 3. 
Feedback requested: or should we mention that xUnit 3 isn't supported yet?
> Ask for xUnit version in GitHub template

- Reqnroll/Infrastructure/ReqnrollOutputHelper.cs
- Tests/Reqnroll.Specs/StepDefinitions/ExecutionResultSteps.cs
Changed ReqnrollOutputHelper to use test output instead of the tool output in `ITraceListener`.
In practice this means that the `->` prefix is not added to this messages.
The `ITraceListener.WriteToolOutput` was intended to provide information that come from the tool (ie Reqnroll), not from the tests, so this was incorrect.
How could it happen that we didn't notice this so far...
----
> Change ReqnrollOutputHelper to use test output

- Tests/Reqnroll.RuntimeTests/ArgumentHelpers.cs
- Tests/Reqnroll.RuntimeTests/StepArgumentTransformationTests.cs
- Tests/Reqnroll.RuntimeTests/StepArgumentTypeConverterTest.cs
- Tests/Reqnroll.RuntimeTests/StepExecutionTestsWithConversions.cs
- Tests/Reqnroll.RuntimeTests/StepExecutionTestsWithConversionsForTables.cs
Refactored the tests, but don't changed the behavior of the tests.
- Remove LegacyStepArgumentTypeConverterExtensions - it's a strange pattern and makes tests hard to understand
-  e.g. `StepArgumentTypeConverterStub.Setup(LegacyStepArgumentTypeConverterExtensions.GetCanConvertMethodFilter` is unclear/vague
- It was sometimes unclear which method we were mocking/assertion (because of the extension)
- Add ArgumentHelpers to avoid to much duplication in the tests and make the tests more readable. 
- Removed dead test code (commented out in the touched files)
- Remove some unused vars in the touched files
- Fixed some spelling in comments
Note, I used Resharper for most actions, e.g. inline method, inline variable etc. 
The POC with the migration to NSubstitute …
> Improve tests to make the migration to NSubstitute easier

- docs/automation/step-definitions.md
Optional is not allowed
Async must return Task
It was unclear if optional parameters are supported
Fixes https://github.com/reqnroll/Reqnroll/issues/509
- My English grammar 
- Is this updated online when this PR is merged?
> Improve docs about step parameters

- Reqnroll/ErrorHandling/ErrorProvider.cs
- Tests/Reqnroll.RuntimeTests/ErrorProviderTests.cs
Include original exception in when throwing a BindingException
Imrprove error message and don't hide the stack when an error occurs. It should help #471 (But I think the catch ArgumentException should still be reworked)
> Include original exception in when throwing a BindingException

- docs/integrations/xunit.md
Added some description about the xUnit parallel algorithm.
The new Conservative is is the default, so if the aggressive mode is not configured, then the user
has now a "expected" behavior. So i described not to switch to conservative mode, but i give
the recommandation to stick to it.
Having something to point on, when the issue is comming up, because some hat explicit configured the aggressive mode.
If you find typos or would like to change a sentence or two, just do it ;)
> chore: Add documentation about the xUnit parallel modes

- CHANGELOG.md
- Plugins/Reqnroll.xUnit.ReqnrollPlugin/XunitTestAssemblyRunnerWithAssemblyFixture.cs
- Tests/Reqnroll.SystemTests/Generation/GenerationTestBase.cs
- Tests/Reqnroll.SystemTests/Generation/XUnitGenerationTest.cs
- Tests/Reqnroll.SystemTests/SystemTestBase.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Driver/ProjectsDriver.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Factories/BindingsGenerator/BaseBindingsGenerator.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Factories/BindingsGenerator/CSharpBindingsGenerator.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Factories/BindingsGenerator/FSharpBindingsGenerator.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Factories/BindingsGenerator/VbBindingsGenerator.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/ProjectBuilder.cs
Changed XUnit test run hook infrastructure to wait for async hooks
Fixes #530 
How could this issue exist for 3 years (introduced in SpecFlow in 2022)?
----
> Fix XUnit async AfterTestRun hook issue

- docs/installation/setup-ide.md
Adding an optional step under `Installation -> Setup IDE -> Setup Rider` in case feature files aren't recognized by the plugin
(https://docs.reqnroll.net/latest/installation/setup-ide.html#setup-rider)
Fixes reqnroll/Reqnroll.Rider#45
I had this issue for quite a while now, I did try to manually create a file type association under `Settings -> Editor -> File Types` in the past but some some reasons it never worked. Maybe I did something wrong or maybe an issue has been fixed in a new Reqnroll or Rider version. I have no idea.
Anyway, I just discovered the Right click -> `Associate with File Type...` in Rider (never noticed it before) and it fixes my issue.
So I thought adding it to the documentation could benefit others.
Not …
> docs(installation/Rider): adding file type association optional step

- CHANGELOG.md
- Plugins/Reqnroll.SpecFlowCompatibility.ReqnrollPlugin/Wrappers/FeatureContext.cs
- Reqnroll.Generator/Generation/UnitTestFeatureGenerator.cs
- Reqnroll.Generator/UnitTestProvider/XUnit2TestGeneratorProvider.cs
- Reqnroll/FeatureContext.cs
- Reqnroll/Infrastructure/TestExecutionEngine.cs
- Reqnroll/TestRunnerManager.cs
- Tests/Reqnroll.RuntimeTests/Infrastructure/TestExecutionEngineTests.cs
- Tests/Reqnroll.RuntimeTests/Infrastructure/TestThreadExecutionEventPublisherTests.cs
- Tests/Reqnroll.RuntimeTests/TestRunnerManagerStaticApiTest.cs
- Tests/Reqnroll.RuntimeTests/TestRunnerManagerTests.cs
- Tests/Reqnroll.SystemTests/Generation/GenerationTestBase.cs
- Tests/Reqnroll.SystemTests/SystemTestBase.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Driver/BindingsDriver.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Helpers/FolderCleaner.cs
- docs/automation/hooks.md
Made sure that every relevant code after a hook call is in a finally block or somehow else ensured that it runs even in a case of a hook error.
Fixes #526 
This issue was introduced in v2.2.0 with support scenario-level (method-level) parallel execution (#119, #277).
----
> Fix: AfterFeature is called as many times as there are scenarios that throw an exception in AfterScenario

- Plugins/Reqnroll.xUnit.Generator.ReqnrollPlugin/Reqnroll.xUnit.nuspec
Changed the description of the xUnit package
- The "xUnit 2.4 and later" was confusing, because the dependency of xUnit 2.8.1+
- Made more clear that xUnit 3 isn't supported
> Improved description of xUnit package

- CHANGELOG.md
- Reqnroll.Generator/Generation/UnitTestFeatureGenerator.cs
Checks in generated feature files that `testRunner` is not null in after scenario hooks (IAsyncLifetime.DisposeAsync/TearDown/TestCleanup). If the testRunner field is null return without a exception.
Hopefully fixes #387
This PR should fix crashes caused by the test framework entering the after scenario hooks multiple times.
If Reqnroll has incorrect TestRunner management, this PR won't fix it.
See also discussion in #550.
Unfortunately, we don't have a sample project that reproduces #387.
Is this the right approach?
Should we add some sort of logging for this (not expected) behavior of the test framework?
----
*This text was originally taken from the [template of the Cucumber …
> Guard when calling AfterScenario when TestRunner is already released

- CHANGELOG.md
- Reqnroll.Generator/CodeDom/CodeDomHelper.cs
- Reqnroll.Generator/Generation/UnitTestFeatureGenerator.cs
- Reqnroll.Generator/Generation/UnitTestMethodGenerator.cs
- Reqnroll.Generator/TestGenerator.cs
Also made all references to Reqnroll and System types as global:: (there were a few that had been missed earlier).
Modified the code generation such that all references to Reqnroll and System types are now global.
Modified code generation so that the file-wide 'using' statements now appear before the declaration of the namespace for the file. (This addresses the adherence to .NET conventions outlined in #582. )
Bug fix. Allows user-provided solution names to be used as generated namespace names without collisions with Reqnroll or System types.
I'm not sure that this works appropriately for VB or F# generation.
- [X ] I have added an entry to the "[vNext]" section of the …
> Fix #582 by moving 'using' directives to be generated before the namespace declaration.

- CHANGELOG.md
- Reqnroll.Generator/UnitTestProvider/MsTestGeneratorProvider.cs
- Tests/Reqnroll.GeneratorTests/UnitTestProvider/MsTestGeneratorProviderTests.cs
... with the result that the friendly name is used by the VS2022 Test Explorer as the name of the test rather than the C# method name.
Changed the MsTestGeneratorProvider SetTestMethod so that the TestMethodAttribute includes the friendly name as the name of the test.
See thread in #574 
- :zap: New feature (non-breaking change which adds new behaviour)
----
> MsTest: adds the test method friendly name to the generated TestMethodAttribute

- CHANGELOG.md
- Reqnroll.Generator/Generation/UnitTestFeatureGenerator.cs
- Reqnroll/ITestRunnerManager.cs
- Reqnroll/TestRunnerManager.cs
- Tests/Reqnroll.SystemTests/Generation/GenerationTestBase.cs
When a feature file cleanup (e.g., ClassCleanup) is called, all available test-runners that match the cleaned up feature execute the `AfterFeature` hook.
Fixes #597
This ensures that errors in the `AfterFeature' hook are raised as they were before #277 was merged.
The error could still occur if another thread grabs the test runner from `_availableTestWorkerContainers` before the test frameworks call the feature file cleanup method.
Perhaps we should have a separate list of available test runners for a feature, and only return the test runner to the global `_availableTestWorkerContainers` when the feature is complete.
I've encountered some cases where the `TestWorkerContainerHint.LastUsedFeatureInfo' and the …
> Fix: Exception in an `AfterFeature` hook causes the next first test failure in the next feature

- docs/integrations/mstest.md
Documentation update regadering MSTest.
Add "generator": {"allowRowTests" :  false} to the documentation for MSTest users as a workaround for Examples: not passing on tags.
Fixes #342 
*no code changed, just docs*
----
> Update doc MSTest regarding generator/tags on examples

- CHANGELOG.md
- Reqnroll/Bindings/BindingMatch.cs
- Reqnroll/ErrorHandling/AmbiguousBindingException.cs
- Reqnroll/ErrorHandling/ErrorProvider.cs
- Reqnroll/Infrastructure/MatchArgumentCalculator.cs
- Reqnroll/Infrastructure/StepDefinitionMatchService.cs
- Reqnroll/Infrastructure/TestExecutionEngine.cs
- Tests/Reqnroll.RuntimeTests/ErrorProviderTests.cs
- Tests/Reqnroll.RuntimeTests/Infrastructure/TestExecutionEngineTests.cs
Changes to the binding matching process such that when an ambiguous match is found, the actual found binding matches are returned as part of the AmbiguousBindingMatchException.
This is in preparation for Cucumber Messages which needs the binding info.
- [X ] I have added/updated tests to cover my changes.
----
> Refactor: Enhance handling of Ambiguous Binding Match situations 

- CHANGELOG.md
- Reqnroll.Generator/Generation/UnitTestFeatureGenerator.cs
- Reqnroll.Generator/Interfaces/TestGeneratorResult.cs
- Reqnroll.Generator/TestClassGenerationContext.cs
- Reqnroll.Generator/TestGenerator.cs
- Reqnroll.Generator/UnitTestConverter/IFeatureGenerator.cs
- Reqnroll.Tools.MsBuild.Generation/FeatureFileCodeBehindGenerator.cs
- Reqnroll.Tools.MsBuild.Generation/TestFileGeneratorResult.cs
- Tests/Reqnroll.GeneratorTests/CustomTestGeneratorProviderTest.cs
- Tests/Reqnroll.GeneratorTests/TestGeneratorTest.cs
- Tests/Reqnroll.GeneratorTests/UnitTestFeatureGeneratorTests.cs
- Tests/Reqnroll.GeneratorTests/UnitTestProvider/MsTestGeneratorProviderTests.cs
- Tests/Reqnroll.GeneratorTests/UnitTestProvider/MsTestV2GeneratorProviderTests.cs
- Tests/Reqnroll.GeneratorTests/UnitTestProvider/NUnit3GeneratorProviderTests.cs
- Tests/Reqnroll.GeneratorTests/UnitTestProvider/XUnit2TestGeneratorProviderTests.cs
The UnitTestFeatureGenerator's GenerateUnitTestFixture method now has an out parameter that is a collection of warnings that the generator has created. These would contain notices about problems that did not cause the generator to fail, but that the resulting Feature Test class may not be fully functional.
In preparation for Cucumber Messages, this was added to allow the generator to signal that there was a problem in processing the Gherkin feature file that may impact Reqnroll's ability to emit Messages.
----
*This text was originally taken from the [template of the Cucumber project](https://github.com/cucumber/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md), then edited by hand. [You …
> Refactor: Add GeneratorWarnings as output parameter of UnitTestFeatureGenerator.

- CHANGELOG.md
- Reqnroll/BoDi/ObjectContainer.cs
- Tests/Reqnroll.RuntimeTests/BoDi/DisposeTests.cs
Throws a exception if `RegisterInstanceAs` or `RegisterFactoryAs` is called on a disposed ObjectContainer instance.
Fix a possible loophole where it's possible for `ObjectContainer.Dispose()` to throw an exception:
- Add a disposable instance to an `ObjectContainer' instance with a reference to the `ObjectContainer.
- Dispose `ObjectContainer
- Call the `RegisterInstanceAs' or `RegisterFactoryAs' method of the `ObjectContainer' in your instance.Dispose() method.
- See exception
Could be a possible cause of #589.
----
*This text was originally taken from the [template of the Cucumber project](https://github.com/cucumber/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md), then edited by hand. [You can modify the template …
> Fix: Disposed ObjectContainer can be accessed through RegisterInstanceAs/RegisterFactoryAs/RegisterTypeAs

- CHANGELOG.md
- Reqnroll.Generator/UnitTestProvider/MsTestV2GeneratorProvider.cs
- Tests/Reqnroll.GeneratorTests/UnitTestProvider/MsTestV2GeneratorProviderTests.cs
Modified MsTestv2GeneratorProvider so that Scenario Outlines (aka, DataRow tests) are provided with a friendly name based upon the Scenario Name and the list of data value arguments.
User friendliness
- :zap: New feature (non-breaking change which adds new behaviour)
Need further discussion on how it should handle large lists of arguments and argument values that are large. Should they be elided?
- [X ] I have added/updated tests to cover my changes.
- [X ] Users should know about my change
- [ X] I have added an entry to the "[vNext]" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request & included my GitHub handle to the release contributors list.
----
*This text was originally taken from the [template of …
> Human readable test names in mstest rowtests

- .github/workflows/ci.yml
- Tests/Reqnroll.GeneratorTests/Reqnroll.GeneratorTests.csproj
- Tests/Reqnroll.PluginTests/Reqnroll.PluginTests.csproj
- Tests/Reqnroll.RuntimeTests/Reqnroll.RuntimeTests.csproj
- Tests/Reqnroll.Specs/Reqnroll.Specs.csproj
- Tests/Reqnroll.SystemTests/Portability/PortabilityTestBase.cs
- Tests/Reqnroll.SystemTests/Reqnroll.SystemTests.csproj
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator.Tests/Reqnroll.TestProjectGenerator.Tests.csproj
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Dotnet/CacheAndCopyCommandBuilder.cs
- RRC cache folder can now also be changed (by changing `REQNROLL_TEST_TEMPFOLDER`)
- Windows: Installed and temporary files are now located on drive D: (test temp folder, dotnet installation, nuget). For background, see https://github.com/actions/setup-dotnet/issues/260
- Opt out of telemetry (Reqnroll and Dotnet) to improve compilation speed (hurts a lot when calling dotnet build etc. for our many generated test projects)
- Cache RRC folder between runs
- For Spec and SystemTest, we reuse the build test assemblies from the "build" job. This avoids recompiling our own nuget and test assemblies (and ensures that we test the nuget packages we have in the artifacts on all platforms).
- Add `GitHubActionsTestLogger` explicitly in csproj (with condition) to improve compilation speed (avoids …
> Improve CI/CD perf and ensure all dotnet versions are tested

- .github/workflows/ci.yml
Added week number to the RRC cache key on CI
The RRC cache depends on the system tests we create. A proper cache key would be generated based on the different package template combinations we use in tests, but it is not feasible to generate that.
Added a week number instead so that the cache is re-calculated every week once, but effective in all build during that week.
Also added a few comments on the existing CI tasks.
----
*This text was originally taken from the [template of the Cucumber project](https://github.com/cucumber/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md), then edited by hand. [You can modify the template here.](https://github.com/reqnroll/.github/edit/main/.github/PUL …
> Add week number to the RRC cache key on CI

- docs/conf.py
Updated years
This looks unmaintained, which we clearly aren't!
> Updated copyright years on Reqnroll Documentation site

- Reqnroll/Formatters/FileWritingFormatterBase.cs
- Tests/Reqnroll.RuntimeTests/Formatters/PubSub/FileWriterBaseTests.cs
Fix for #690  to properly add the default extension when none given and not overwrite one already present.
----
> Fix for 690 to properly add the default extension

- Reqnroll/Formatters/Message/MessageFormatter.cs
- Reqnroll/Infrastructure/DefaultDependencyProvider.cs
- Tests/Reqnroll.Formatters.Tests/MessagesCompatibilityTestBase.cs
- Tests/Reqnroll.Formatters.Tests/reqnroll.json
- Tests/Reqnroll.Formatters.Tests/reqnrollConfigurationWithExternalAssembly.json
- Tests/Reqnroll.Formatters.Tests/reqnroll_withBothFormatters.json
- Tests/Reqnroll.RuntimeTests/Formatters/Configuration/EnvironmentConfigurationResolverTests.cs
Corrected naming of the MessageFormatter to match the form of the word as used by the Cucumber ecosystem.
To stay aligned with the Cucumber project.
----
> Corrected naming of the MessageFormatter 

- .github/workflows/ci.yml
- moved from normal to minimal
- no-restore on dotnet test
this still logs warnings
https://learn.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2019#verbosity-settings
logs of 2000+ lines are hard to read 
CI build performance
the restore check is a NOOP, but confusing in logs - I like to check the dotnet rest results, not a NOOP restore
quiet is also an option, but not that much benefit, So minimal is fine
logging:
2500+ lines 
~410 lines, but not really useful
at lot of "default config"
~380 lines
not very different to minimal
> dotnet test - less verbose logging & no-restore

- CHANGELOG.md
- Plugins/Reqnroll.Microsoft.Extensions.DependencyInjection.ReqnrollPlugin/InvalidScenarioDependenciesException.cs
- Plugins/Reqnroll.Microsoft.Extensions.DependencyInjection.ReqnrollPlugin/MissingScenarioDependenciesException.cs
- Plugins/Reqnroll.xUnit.ReqnrollPlugin/XUnitInconclusiveException.cs
- Plugins/Reqnroll.xUnit.ReqnrollPlugin/XUnitPendingStepException.cs
- Reqnroll.Generator/TestGeneratorException.cs
- Reqnroll/BoDi/ObjectContainerException.cs
- Reqnroll/ErrorHandling/AmbiguousBindingException.cs
- Reqnroll/ErrorHandling/BindingException.cs
- Reqnroll/ErrorHandling/ColumnCouldNotBeBoundException.cs
- Reqnroll/ErrorHandling/MissingStepDefinitionException.cs
- Reqnroll/ErrorHandling/ReqnrollException.cs
- Removed [Serializable] from exceptions, and only from exceptions
- For those types:
- Removed constructors with SerializationInfo on exceptions - there are no results anymore for the search text "SerializationInfo" in this solution
-   Removed GetObjectData methods - there are no results anymore for the search text "GetObjectData" in this solution
-  Removed `using System.Runtime.Serialization`, there is also no result for the search text "System.Runtime.Serialization" in this solution
Also improved a null property, see comment of Copilot
Fixes #736 
> Remove [Serializable] from exceptions, including serialisation constructors

- Reqnroll/Formatters/FormatterBase.cs
Dispose cancellationTokenSource in FormatterBase.Dispose()
Found this with a SonarQube analysis.
CancellationTokenSource is disposeable and also the docs says we should dispose
https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource?view=net-9.0
> Dispose cancellationTokenSource in FormatterBase

- CHANGELOG.md
- Reqnroll.Generator/Generation/UnitTestMethodGenerator.cs
- Tests/Reqnroll.GeneratorTests/ParserHelper.cs
- Tests/Reqnroll.GeneratorTests/UnitTestFeatureGeneratorTests.cs
Modified UnitTestFeatureGenerator to include Rule tags when generating TestCategory attributes.
This fixes #731 
----
> Tags on rules should be generated as test categories (#731)

- Reqnroll/Events/ExecutionEvent.cs
- Reqnroll/Formatters/ExecutionTracking/HookStepExecutionTracker.cs
- Reqnroll/Formatters/ExecutionTracking/StepTrackerFactory.cs
- Reqnroll/Infrastructure/TestExecutionEngine.cs
- Tests/Reqnroll.Formatters.Tests/MessagesCompatibilityTests.cs
- Tests/Reqnroll.RuntimeTests/Formatters/ExecutionTracking/FeatureExecutionTrackerTests.cs
- Tests/Reqnroll.RuntimeTests/Formatters/ExecutionTracking/HookStepExecutionTrackerTests.cs
- Tests/Reqnroll.RuntimeTests/Formatters/ExecutionTracking/PickleExecutionTrackerTests.cs
- Tests/Reqnroll.RuntimeTests/Formatters/PubSub/FormatterPublisherTests.cs
- Tests/Reqnroll.RuntimeTests/Infrastructure/TestThreadExecutionEventPublisherTests.cs
A Hook step is now shown as Skipped when it throws an exception from a unit test provider that indicates that the test should be skipped. (instead of indicating TestError)
The 'Skipped' CCK scenario now passes!
Fixes #750 
Compliance with the CCK
----
> Fixed handling of dynamically skipped scenarios caused by a Hook (#750)

- CHANGELOG.md
- Reqnroll/Infrastructure/ContextManager.cs
- Reqnroll/ReqnrollContext.cs
- Tests/Reqnroll.RuntimeTests/Infrastructure/ContextManagerTests.cs
- Tests/Reqnroll.RuntimeTests/Infrastructure/TestThreadContextTests.cs
Modified registration of Scenario, Feature and TestThreadContext so that they can be additionally resolved or injected through their interfaces as well. E.g. with the change this should be allowed:
```c#
[Binding]
public sealed class CalculatorStepDefinitions
{
private readonly IScenarioContext _scenarioContext;
public CalculatorStepDefinitions(IScenarioContext scenarioContext)
{
_scenarioContext = scenarioContext;
}
[...]
}
```
I have added a couple of tests for the context initializations that were missing.
Depending on the interface is cleaner, plus this is needed for improved DI (see https://github.com/gasparnagy/Reqnroll-DiPluginPrototype/blob/e989fae567ee8693844452d8347b2848647a341c/ReqnrollPlugins.DependencyInjection/ToReqnroll/Runtime/Setup.cs?plain=1#L19C1-L19C56)
- :zap: New …
> Allow Scenario, Feature and TestThreadContext to be resolved with their interfaces

- CHANGELOG.md
- Plugins/Reqnroll.Assist.Dynamic/Reqnroll.Assist.Dynamic/Reqnroll.Assist.Dynamic.nuspec
- Plugins/Reqnroll.Autofac.ReqnrollPlugin/Reqnroll.Autofac.nuspec
- Plugins/Reqnroll.CustomPlugin/Reqnroll.CustomPlugin.nuspec
- Plugins/Reqnroll.ExternalData/Reqnroll.ExternalData.ReqnrollPlugin/Reqnroll.ExternalData.nuspec
- Plugins/Reqnroll.MSTest.Generator.ReqnrollPlugin/Reqnroll.MSTest.nuspec
- Plugins/Reqnroll.Microsoft.Extensions.DependencyInjection.ReqnrollPlugin/Reqnroll.Microsoft.Extensions.DependencyInjection.nuspec
- Plugins/Reqnroll.NUnit.Generator.ReqnrollPlugin/Reqnroll.NUnit.nuspec
- Plugins/Reqnroll.SpecFlowCompatibility.Generator.ReqnrollPlugin/Reqnroll.SpecFlowCompatibility.nuspec
- Plugins/Reqnroll.TUnit.Generator.ReqnrollPlugin/Reqnroll.TUnit.nuspec
- Plugins/Reqnroll.Verify/Reqnroll.Verify.ReqnrollPlugin/Reqnroll.Verify.nuspec
- Plugins/Reqnroll.Windsor.ReqnrollPlugin/Reqnroll.Windsor.nuspec
- Plugins/Reqnroll.xUnit.Generator.ReqnrollPlugin/Reqnroll.xUnit.nuspec
- Reqnroll.Tools.MsBuild.Generation/Reqnroll.Tools.MsBuild.Generation.nuspec
Remove the `<summary>`
Plugins/Reqnroll.Assist.Dynamic/Reqnroll.Assist.Dynamic/Reqnroll.Assist.Dynamic.nuspec: 
Moved content from `<summary>` to `<description>`
It's deprecated and it's not visible on nuget.org anymore
https://learn.microsoft.com/en-us/nuget/reference/nuspec#summary
Also saves some keeping things in-sync / keeping them both up-to-date
Fixes also these warnings when validating packages:
I checked the logs that I have fixed all the packages
> Removed deprecated `<summary>` from NuGet packages

- CHANGELOG.md
- Reqnroll/Formatters/FileWritingFormatterBase.cs
- Tests/Reqnroll.RuntimeTests/Formatters/FileWritingFormatterBaseTests.cs
Refactored FileWritingFormatterBase more robustly handle empty or missing configuration.
Fix #797 
----
> File formatter fails under net462 when output file path is empty

- CHANGELOG.md
- Reqnroll.Tools.MsBuild.Generation/build/Reqnroll.Tools.MsBuild.Generation.targets
Removed a leftover build message that has been introduced for debug purposes by #802.
Currently Reqnroll shows extra messages during build.
```
2>------ Build started: Project: ReqnrollCalculator.Specs, Configuration: Debug Any CPU ------
2>ReqnrollGeneratedNdjsonFiles: obj\Debug\net8.0\Features\Addition.feature.ndjson;obj\Debug\net8.0\Features\Multiplication.feature.ndjson    <-----
2>ReqnrollCalculator.Specs -> C:\Users\GáspárNagy\source\repos\Reqnroll.ExploratoryTestProjects\ReqnrollCalculator\ReqnrollCalculator.Specs\bin\Debug\net8.0\ReqnrollCalculator.Specs.dll
```
----
*This text was originally taken from the [template of the Cucumber project](https://github.com/cucumber/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md), …
> Remove unnecessary build message

- CHANGELOG.md
- Reqnroll/Infrastructure/TestExecutionEngine.cs
- Tests/Reqnroll.RuntimeTests/Infrastructure/TestExecutionEngineRuntimePluginEventsTests.cs
Fix #856: Exceptions from before scenario plugin hook events (RuntimePluginTestExecutionLifecycleEvents.BeforeScenario) are not shown
Also fixed a closely related bug:
* Before scenario hooks are not raised immediately when `runtime/stopAtFirstError` is true, but handled delayed
#856 
This is a regression issue in v3.0.0
----
> Fix: Exceptions from before scenario plugin hook events are not shown

- CHANGELOG.md
- Reqnroll.Generator/UnitTestProvider/MsTestV2GeneratorProvider.cs
- Tests/Reqnroll.GeneratorTests/UnitTestProvider/MsTestV2GeneratorProviderTests.cs
This PR honors the DisableFriendlyTestNames configuration setting to omit the DisplayName property when that config value is true.
MsTest row tests are given a DisplayName that is inconsistent with that provided by Reqnroll v2. This causes problems with test filtering in CI jobs. 
Fixes #867 
----
> Omit DisplayName property for MsTest row tests when DisableFriendlyTestNames config is true

- Tests/Reqnroll.SystemTests/ExternalPlugins/ReportPortalPluginTest.cs
- Tests/Reqnroll.SystemTests/ExternalPlugins/Resources/ReportPortalPlugin/ReportPortal.config.json
- Tests/Reqnroll.SystemTests/ExternalPlugins/Resources/ReportPortalPlugin/ReportPortalPluginTestFeature.feature
Add integration tests that verify [ReportPortal.Reqnroll](https://github.com/reportportal/agent-dotnet-reqnroll) plugin compatibility with Reqnroll. These tests reproduce the previous incompatibility and will guard against regressions going forward.
> Add integration tests for ReportPortal.Reqnroll plugin compatibility
