- docs/guides/driver-pattern.md
Fixed link to David Leitner's blog post "Driver Pattern empowers your SpecFlow step definitions" on the "Using the Driver Pattern" documentation page.
> Fix resource link in: Update driver-pattern.md

- Plugins/Reqnroll.ExternalData/sample/ExternalDataSample/StepDefinitions/PricingStepDefinitions.cs
Update the unknown special character with the euro symbol. 
This is affecting existing test scenarios, causing them to not be executed.
> Replace special character to euro symbol

- .github/workflows/ci.yml
This fixes the issue introduced with #28.
(It seems to be a known issue: https://github.com/dorny/test-reporter/issues/343)
> Fix test report by downgrading 'upload-artifact'

- CHANGELOG.md
- Reqnroll.Generator/UnitTestProvider/MsTestV2GeneratorProvider.cs
- Tests/Reqnroll.GeneratorTests/UnitTestProvider/MsTestV2GeneratorProviderTests.cs
- docs/integrations/mstest.md
This pr adds the support for PriorityAttribute of the MsTest framework
- [x ] New feature (non-breaking change which adds functionality).
- [ x] I've added tests for my code. (most of the time mandatory)
- [ x] I have added an entry to the changelog. (mandatory)
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
> supported PriorityAttribute for MsTest #41

- docs/help/samples.md
I added my sample PlayWright in the samples section.
- [ x] Other (docs, build config, etc)
- [ x] I have added an entry to the changelog. (mandatory)
- [ x] I have updated the documentation accordingly.
> Update samples.md with sample PlayWright project

- docs/guides/migrating-from-specflow.md
> Fixed typo

- Tests/Reqnroll.SystemTests/Portability/PortabilityTestBase.cs
> Add NUnit & xUnit core tests to portability suite

- CHANGELOG.md
- Plugins/Reqnroll.xUnit.Generator.ReqnrollPlugin/build/Reqnroll.xUnit.targets
> Fix: xUnit .NET framework Reqnroll projects might not run BeforeTestRun even with the fix for #146 (causing flaky CI)

- .gitignore
- CHANGELOG.md
- Plugins/Reqnroll.ExternalData/Reqnroll.ExternalData.ReqnrollPlugin.IntegrationTest/Reqnroll.ExternalData.ReqnrollPlugin.IntegrationTest.csproj
- Plugins/Reqnroll.Verify/Reqnroll.Verify.ReqnrollPlugin.IntegrationTest/Reqnroll.Verify.ReqnrollPlugin.IntegrationTest.csproj
- Reqnroll.Tools.MsBuild.Generation/build/Reqnroll.Tools.MsBuild.Generation.tasks
- Tests/Reqnroll.Specs/Reqnroll.Specs.csproj
- Tests/Reqnroll.Specs/build/Reqnroll.Tools.MsBuild.Generation.OwnTests.props
- Tests/Reqnroll.Specs/build/Reqnroll.Tools.MsBuild.Generation.OwnTests.tasks
> Fix: Building a Reqnroll project on macOS ARM64 architecture (eg MacBook M1) fails

- CHANGELOG.md
- Directory.Build.props
- Directory.Build.targets
- Plugins/Reqnroll.Autofac.ReqnrollPlugin/Reqnroll.Autofac.nuspec
- Plugins/Reqnroll.ExternalData/Reqnroll.ExternalData.ReqnrollPlugin/Reqnroll.ExternalData.nuspec
- Plugins/Reqnroll.Microsoft.Extensions.DependencyInjection.ReqnrollPlugin/Reqnroll.Microsoft.Extensions.DependencyInjection.nuspec
- Plugins/Reqnroll.Verify/Reqnroll.Verify.ReqnrollPlugin/Reqnroll.Verify.nuspec
- Plugins/Reqnroll.Windsor.ReqnrollPlugin/Reqnroll.Windsor.nuspec
- docs/extend/plugins.md
- docs/installation/compatibility.md
This PR specifies our versioning policy and updates the versioning policy for Reqnroll plugins.
Also changes the dependency specification of the plugins accordingly.
> Update plugin versioning policy

- Tests/Reqnroll.Specs/Support/Hooks.cs
- Tests/Reqnroll.SystemTests/SystemTestBase.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator.Cli/GenerateSolutionParams.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator.Cli/Program.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator.Tests/AppConfigGeneratorTests.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator.Tests/JsonConfigGeneratorTests.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/CurrentVersionDriver.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Driver/ConfigurationFileDriver.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Driver/SolutionDriver.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/Extensions/UnitTestProviderExtensions.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/ProjectBuilder.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/TRXParser.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/UnitTestProvider.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/VSTestExecutionDriver.cs
remove unused SpecRun support from TestProjectGenerator
simplify code base
----
> remove unused SpecRun support from TestProjectGenerator

- Tests/Reqnroll.SystemTests/Generation/GenerationTestBase.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/TRXParser.cs
Added a new test to the System Tests suite to verify background steps (both feature-scoped and rule-scoped) are invoked by the runner.
This change is to support the further testing of the Roslyn code-generator, however it has value as a stand-alone test to expand the coverage of the System Tests suite.
I made a change to the System Tests infrastructure to parse out the executed steps from the standard output logs. It's not especially "clean" or obviously robust code; there may be better solutions I haven't considered.
----
*This text was originally taken from the [template of the Cucumber project](https://github.com/cucumber/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md), then edited …
> Add background-based tests to system tests

- Tests/Reqnroll.SystemTests/Generation/GenerationTestBase.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/TRXParser.cs
- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/TestExecutionResult.cs
Added a system test to cover passing table arguments to step methods.
Extends the system test coverage to assist with the development of Roslyn-based generator.
----
> Add test for table arguments being passed to steps

- CHANGELOG.md
- Reqnroll.Parser/Reqnroll.Parser.csproj
- Reqnroll/Reqnroll.csproj
- Reqnroll/Reqnroll.nuspec
- Update Gherkin parser to 30.0.0
- Dependency update
n\a
----
> Update Gherkin to 30.0.0

- CHANGELOG.md
- Tests/Reqnroll.Specs/MSTestConfiguration.cs
- Tests/Reqnroll.Specs/Reqnroll.Specs.csproj
- Tests/Reqnroll.Specs/xUnitConfiguration.cs
This PR changes the internal Reqnroll.Specs test project from xUnit to MSTest and enable scenario level parallelism.
With this PR, the execution time of the Specs project changes from ~3.5 minutes to ~1.6 minutes on my machine.
In the Specs project we have some feature files with many scenarios (e.g. ExecuteHooksFeature with 55 scenarios). With this PR we can now run these tests in parallel instead of sequentially.
This helps to get the most out of modern CPUs (e.g. the 24 cores on my machine). I don't expect much change in the CI (4 cores).
----
*This text was originally taken from the [template of the Cucumber project](https://github.com/cucumber/.github/blob/main/.github/PULL_REQUEST_TEMP …
> Specs: Change from xUnit feature level parallelism to MSTest scenario level parallelism.

- Tests/Reqnroll.RuntimeTests/AssistTests/CreateInstanceHelperMethodTests.cs
- docs/automation/datatable-helpers.md
Added docs for `InstanceCreationOptions`
fixes #514 
Also changed one test to assert the message
- My English grammer, feel free to edit it in this PR - I will check the changes
- It was a bit hard to find the correct spot for this doc in the page. Also FillInstance isn't documented, but that's another issue IMO (==> https://github.com/reqnroll/Reqnroll/issues/528)
> Docs for `InstanceCreationOptions`

- LICENSE
Added current year to license file
Looks more maintained 
We could also drop the year in the license file?
> Update LICENSE years

- Tests/TestProjectGenerator/Reqnroll.TestProjectGenerator/ProjectBuilder.cs
Updated MsTest to 2.2.10 in our CI/CD pipeline.
Hopefully this fixes the build errors.
It could be related to https://github.com/microsoft/testfx/pull/1020 that was included in 2.2.9.
Should we updated our dependencies to newer versions in the tests?
This would ensure that we run with the latest dependencies.
----
> Fix: use updated/fixed ms test in ProjectBuilder.cs

- CHANGELOG.md
- Reqnroll.Utils/FileSystem.cs
- Reqnroll.Utils/IFileSystem.cs
- Tests/Reqnroll.GeneratorTests/VirtualFileSystem.cs
Enhances the abstract file system in IFileSystem with a CreateDirectory method.
This file system abstraction will be used by Cucumber Messages. This PR does not yet cause Reqnroll project to take a project dependency on Reqnroll.Utils, but the CucumberMessages PR will make that so.
There is another File System abstraction built in to Reqnroll/Analytics/UserId that is almost a complete duplicate of this one. Should these be merged? Which one should be eliminated? What namespace should it be within?
Are there any objections to have the Reqnroll core project take a project dependency on Reqnroll.Utils?
- [X ] I have added/updated tests to cover my …
> Refactor: Add CreateDirectory() method to Reqnroll.Util/IFileSystem

- docs/execution/dry-run.md
Added a note that Dry Run is a v3 feature
I really like this feature (introduced in https://github.com/reqnroll/Reqnroll/pull/614), but as the docs are live, it looks supported for v2
See https://docs.reqnroll.net/latest/execution/dry-run.html
#
> Added a note that Dry Run is a v3 feature

- docs/execution/dry-run.md
Fixing some typos in the `dry-run.md` file.
Clarity in documentation.
N/A
> Fixing some typos in dry-run.md

- Reqnroll/Reqnroll.nuspec
removed unused nuspec file reference. reqnroll.bodi is not a separate project anymore
not needed
----
> remove unused nuspec file reference. reqnroll.bodi is not a separate project anymore

- docs/conf.py
Made the years dynamic for the docs site
test it locally with ` .\make.cmd html`
It will be up-to-date when we publish new docs :)
follow up of https://github.com/reqnroll/Reqnroll/pull/645
> Make years in docs update "automatically"

- Plugins/Reqnroll.TUnit.Generator.ReqnrollPlugin/TUnitTestGeneratorProvider.cs
- Tests/Reqnroll.SystemTests/Generation/GenerationTestBase.cs
- Tests/Reqnroll.SystemTests/Generation/TUnitTestGenerationTest.cs
- Configure `DisplayName` as described in this [discussion](https://github.com/reqnroll/Reqnroll/issues/674#issuecomment-3143951688)
- Used ignore tag for handling ignored row tests (`TagHelper.ContainsIgnoreTag`)
Fixes #674 and supports ignore tag in row tests (needed to enable `Handles_different_scenario_and_scenario_outline_outcomes`.)
----
> TUnit: show parameters and support @ignore tag in row tests
